apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rhopp-test-go-251204
  janus-idp.io/tekton: rhopp-test-go-251204
  backstage.io/kubernetes-id: rhopp-test-go-251204
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rhopp-test-go-251204
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
