apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhopp-test-go-251204
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhopp-test-go-251204 
  name: rhopp-test-go-251204
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhopp-test-go-251204 
